CONTAINER Opyspherifydeformer
{
	NAME Opyspherifydeformer;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PYSPHERIFYDEFORMER_RADIUS	   { UNIT METER; MIN 0.0; }
		REAL PYSPHERIFYDEFORMER_STRENGTH	 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
	}
}
